### PR TITLE
Add Pirmin changes

### PR DESCRIPTION
**Pull request by GLP90**

### CODE REVIEW

**Comment by perrozzi** [comment]
I suggest to start using the master branch as the central one :-)

**Comment by GLP90** [comment]
Yes sure, piberger:master should be the central one.
 It's just that I synchronised my merge_silvio branch with the one from Pirmin (instead of making a new one starting from Pirmin master branch).

**Comment by perrozzi** [comment]
(not sure I was clear, I meant to suggest you to use your master branch https://github.com/GLP90/Xbb/tree/master instead of merge_silvio :-) )

**Comment by GLP90** [comment]
Ok done ("master" is now my main branch with all the latest change)

**Pull request merged**
